---

- hosts: all
  become: true
  tasks:

# *buntu section     
  - name: install curl and wget (gets stuffs)
    package:
      name:
        - "{{ curl_dist_pkg }}"
        - "{{ wget_dist_pkg }}"  
      state: latest
      update_cache: yes  

  - name: feh (shows pics)
    package:
      name:
        - "{{ feh_disto_pkg}}"
      state: latest
      update_cache: yes  

  - name: flatpak snap docker (apps not dist specific)
    package:
      name: 
        - "{{ flatpak_dist_pkg }}" 
        - "{{ snap_dist_pkg }}"
        - "{{ docker_dist_pkg }}"    
      state: latest
      update_cache: yes    

  - name: git (build stuff)
    package:
      name: 
  - "{{ git_dist_pkg }}"
      state: latest
      update_cache: yes  

  - name: htop iotop inxi (prettier monitoring)
    package:
      name: 
        - "{{ htop_dist_pkg }}" 
        - "{{ iotop_dist_pkg }}"  
        - "{{ inxi_dist_pkg }}"
      state: latest
      update_cache: yes    
      
  - name: nfs-common (access nfs shares)
    package:
      name:
        - "{{ nfs-common_dist_pkg }}" 
      state: latest
      update_cache: yes  

  - name: openssh-server (remote access)
    package:
      name:
        - "{{ openssh-server_dist_pkg }}" 
      state: latest
      update_cache: yes  

  - name: tmux (teminal multiplexer so I can detach, mostly)  
    package:
      name: 
        - "{{ tmux_dist_pkg }}"
      state: latest
      update_cache: yes  
   
  - name: vim (to edit text)
    package:
      name: 
  - "{{ vim_dist_pkg }}"
      state: latest
      update_cache: yes  
   
  - name: zsh (shell with some niceties)
    package:
      name: 
  - "{{ zsh_dist_pkg }}"
      state: latest
      update_cache: yes  
