---

- hosts: all
  become: true
  tasks:

    - name: install updates (Fedora)
      dnf:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "Fedora" 

    - name: install updates (Pop)
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Pop!_OS"

    - name: install updates (*buntu)
      apt:
       upgrade: dist
       update_cache: yes
      when: ansible_distribution == "Ubuntu"       
       
    - name: update flatpaks
      shell:
        cmd: flatpak update --noninteractive
      when: ansible_distribution == "Ubuntu" 

    - name: update flatpaks
      shell:
        cmd: flatpak update --noninteractive
      when: ansible_distribution == "Fedora"

    - name: update flatpaks
      shell:
        cmd: flatpak update --noninteractive
      when: ansible_distribution == "Pop!_OS" 

    - name: update snaps
      shell:
        cmd: snap refresh
      when: ansible_distribution == "Pop!_OS"    

    - name: update snaps
      shell:
        cmd: snap refresh
      when: ansible_distribution == "Ubuntu" 

    - name: update snaps
      shell:
        cmd: snap refresh 
      when: ansible_distribution == "Fedora"  
